## Hello

Here is another exciting football (soccer) project!

Let's start by importing the libraries and pandas setup.

In [102]:
# import libraries
    # for getting and parsing webpages
from bs4 import BeautifulSoup
import requests

    # for EDA and other functions
import pandas as pd
import numpy as np

    # pickle
import pickle

# pandas setup
pd.set_option('display.max_columns', 60)
pd.set_option('display.max_rows', 1000)
pd.set_option('display.precision', 3)

### Scrape

I want to use Baeutiful Soup to scrape the sites.  The sofifa.com/players lists 60 players on a given page. The end of url is identified by the "offset=a_number", a_number = multiplies of 60 starting from 0.  I can use that in a loop to list the pages. The last page's link ends with 19980.

In [103]:
# player url loop
footballer_urls = []
for i in range(0, 19881, 60):
    url = 'https://sofifa.com/?showCol%5B0%5D=ae&showCol%5B1%5D=hi&showCol%5B2%5D=wi&showCol%5B3%5D=pf&showCol%5B4%5D=oa&showCol%5B5%5D=pt&showCol%5B6%5D=bp&showCol%5B7%5D=vl&showCol%5B8%5D=wg&showCol%5B9%5D=ta&showCol%5B10%5D=cr&showCol%5B11%5D=fi&showCol%5B12%5D=he&showCol%5B13%5D=sh&showCol%5B14%5D=vo&showCol%5B15%5D=ts&showCol%5B16%5D=dr&showCol%5B17%5D=cu&showCol%5B18%5D=fr&showCol%5B19%5D=lo&showCol%5B20%5D=bl&showCol%5B21%5D=to&showCol%5B22%5D=ac&showCol%5B23%5D=sp&showCol%5B24%5D=ag&showCol%5B25%5D=re&showCol%5B26%5D=ba&showCol%5B27%5D=tp&showCol%5B28%5D=so&showCol%5B29%5D=ju&showCol%5B30%5D=st&showCol%5B31%5D=sr&showCol%5B32%5D=ln&showCol%5B33%5D=te&showCol%5B34%5D=ar&showCol%5B35%5D=in&showCol%5B36%5D=po&showCol%5B37%5D=vi&showCol%5B38%5D=pe&showCol%5B39%5D=cm&showCol%5B40%5D=td&showCol%5B41%5D=ma&showCol%5B42%5D=sa&showCol%5B43%5D=sl&showCol%5B44%5D=tg&showCol%5B45%5D=gd&showCol%5B46%5D=gh&showCol%5B47%5D=gk&showCol%5B48%5D=gp&showCol%5B49%5D=gr&offset={}'    
    footballer_urls.append(url.format(i))

In [104]:
# check number of urls in the list.
len(footballer_urls)

332

I expect the total number of footballers to be close to 20K (334 pages x 60 footballers per page).

In [105]:
# scrape the footballers data and store in dictionary

footballers = {}
for footballer_url in footballer_urls:    
    
    response = requests.get(footballer_url)
    page = response.text
    soup = BeautifulSoup(page,"lxml")
    table = soup.find('table')
    rows = [row for row in table.find_all('tr')]
    
    # get the number of rows under 'tr' and automate the upper range
    number_of_rows = len(table.findAll(lambda tag: tag.name == 'tr' and tag.findParent('table') == table))
    
    for i in range(1,number_of_rows):    # start the range from 1 to avoid the headers, I'll get them seperately
        name = rows[i].find_all('td')[1].find_all('a')[0]['data-tooltip']
        name_short = str(rows[i].find_all('td')[1].find('div').text).strip()
        team = rows[i].find_all('td')[5].find('a').text
        nationality = rows[i].find_all('td')[1].find('a').find('img')['title']
    
        attribute_points = rows[i].find_all('td')
          
        footballers[name] = [name_short, team, nationality] + \
        [j.text for j in attribute_points[2:5]] + \
        [j.text for j in attribute_points[6:]]

In [106]:
# count check
len(footballers)

18936

This process takes about 5 minutes. Let's pickle (What if lights go out!)

In [107]:
with open('../../Data/EPL-Wage-Estimator/playersData.pkl', 'wb') as picklefile:
    pickle.dump(footballers, picklefile)

##### *A note on the possible missing records: 
*There is a chance it can be due to the name duplication.*

*In order to minimize the name related duplication, I scraped the complete names (first and last name). The total record count is over 19K.*

Here is the column headers preparation. Automation considers order...order matters!

In [108]:
# get column headers of 53 blocks of features

# define one of the url for column headers
url = 'https://sofifa.com/players?showCol%5B0%5D=ae&showCol%5B1%5D=hi&showCol%5B2%5D=wi&showCol%5B3%5D=pf&showCol%5B4%5D=oa&showCol%5B5%5D=pt&showCol%5B6%5D=bp&showCol%5B7%5D=vl&showCol%5B8%5D=wg&showCol%5B9%5D=ta&showCol%5B10%5D=cr&showCol%5B11%5D=fi&showCol%5B12%5D=he&showCol%5B13%5D=sh&showCol%5B14%5D=vo&showCol%5B15%5D=ts&showCol%5B16%5D=dr&showCol%5B17%5D=cu&showCol%5B18%5D=fr&showCol%5B19%5D=lo&showCol%5B20%5D=bl&showCol%5B21%5D=to&showCol%5B22%5D=ac&showCol%5B23%5D=sp&showCol%5B24%5D=ag&showCol%5B25%5D=re&showCol%5B26%5D=ba&showCol%5B27%5D=tp&showCol%5B28%5D=so&showCol%5B29%5D=ju&showCol%5B30%5D=st&showCol%5B31%5D=sr&showCol%5B32%5D=ln&showCol%5B33%5D=te&showCol%5B34%5D=ar&showCol%5B35%5D=in&showCol%5B36%5D=po&showCol%5B37%5D=vi&showCol%5B38%5D=pe&showCol%5B39%5D=cm&showCol%5B40%5D=td&showCol%5B41%5D=ma&showCol%5B42%5D=sa&showCol%5B43%5D=sl&showCol%5B44%5D=tg&showCol%5B45%5D=gd&showCol%5B46%5D=gh&showCol%5B47%5D=gk&showCol%5B48%5D=gp&showCol%5B49%5D=gr&showCol%5B50%5D=0&offset=0'    

response = requests.get(url)
page = response.text
soup = BeautifulSoup(page,"lxml")
table = soup.find('table')

name = table.find_all('th')[1].text
age = table.find_all('th')[2].text
columns = table.find_all('th')
titles = ['name_short', 'Team', 'Nationality', 'Age'] + \
        [j.text for j in columns[3:5]] + \
        [j.text for j in columns[6:]]

len(titles)
#titles

53

In [109]:
# set column headers to lower case
titles = [x.lower() for x in titles]
titles

['name_short',
 'team',
 'nationality',
 'age',
 'ova',
 'pot',
 'height',
 'weight',
 'foot',
 'bp',
 'value',
 'wage',
 'attacking',
 'crossing',
 'finishing',
 'heading accuracy',
 'short passing',
 'volleys',
 'skill',
 'dribbling',
 'curve',
 'fk accuracy',
 'long passing',
 'ball control',
 'movement',
 'acceleration',
 'sprint speed',
 'agility',
 'reactions',
 'balance',
 'power',
 'shot power',
 'jumping',
 'stamina',
 'strength',
 'long shots',
 'mentality',
 'aggression',
 'interceptions',
 'positioning',
 'vision',
 'penalties',
 'composure',
 'defending',
 'marking',
 'standing tackle',
 'sliding tackle',
 'goalkeeping',
 'gk diving',
 'gk handling',
 'gk positioning',
 'gk reflexes',
 'hits']

In [110]:
# fit data into Pandas df

playersData = pd.DataFrame.from_dict(footballers, orient='index', columns=titles).reset_index()

# rename the "name" column
playersData.rename(columns={'index': "name"}, inplace=True)

# perform sanity check (60 footballers per page x 334 pages = )
playersData.shape

(18936, 54)

In [111]:
playersData.head(3)

,name,name_short,team,nationality,age,ova,pot,height,weight,foot,bp,value,wage,attacking,crossing,finishing,heading accuracy,short passing,volleys,skill,dribbling,curve,fk accuracy,long passing,ball control,movement,acceleration,sprint speed,agility,reactions,balance,power,shot power,jumping,stamina,strength,long shots,mentality,aggression,interceptions,positioning,vision,penalties,composure,defending,marking,standing tackle,sliding tackle,goalkeeping,gk diving,gk handling,gk positioning,gk reflexes,hits
0,Paulo Henrique Chagas de Lima,19 Ganso,Amiens SC,Brazil,28,75,75,"6'0""",172lbs,Left,CAM,€6.5M,€20K,361,77,72,56,81,75,398,80,80,76,79,83,259,36,34,68,67,54,304,77,29,56,67,75,328,56,47,71,78,76,75,90,31,29,30,53,9,12,7,11,\n3K
1,Brandon Williams,B. Williams,Manchester United,England,18,71,86,"6'0""",154lbs,Right,LB,€4.5M,€14K,298,63,54,59,69,53,288,72,57,30,59,70,371,79,84,76,68,64,326,68,72,74,62,50,317,80,71,65,60,41,70,202,68,67,67,48,10,13,7,7,\n2K
2,Alejandro Gómez,A. Gómez,Atalanta,Argentina,31,86,86,"5'6""",150lbs,Right,CAM,€39M,€100K,356,83,80,38,83,72,405,85,82,79,74,85,450,94,85,92,85,94,343,76,70,70,46,81,337,56,40,82,87,72,85,114,50,30,34,46,8,11,9,6,\n1.9K

Looks good. Now, I want to drop some more features. I see the grouped sum of attributes in features like `attacking`, `skill`, `movement`,... They are redundant beacuse they will cause collinearity and vialoate linear regression assumption # 5. And I want to drop `hits` as well. It does not add anythng to this project.

In [112]:
playersData.drop(['attacking', 'skill', 'movement', 'power',
                  'mentality', 'defending', 'goalkeeping', 'hits'],
                 axis=1, inplace=True)

And I want to quantify the `weight` and `height`.

In [113]:
# define height conversion dictionary
height_dict = {'5\'10"': 177.80, '5\'11"': 180.34, '5\'4"': 162.56, '5\'5"': 165.10, '5\'6"': 167.64, '5\'7"': 170.18,
               '5\'8"': 172.72, '5\'9"': 175.26, '6\'0"': 182.88, '6\'1"': 185.42, '6\'2"': 187.96, '6\'3"': 190.50,
               '6\'4"': 193.04, '6\'5"': 195.58, '6\'6"': 198.12, '6\'7"': 200.66}

# add metric height
playersData['height_temp'] = playersData['height'].map(height_dict)

# add weigth
playersData['weight_temp'] = playersData['weight'].str[:-3]
playersData['weight_temp'] = playersData['weight_temp'].astype(str).astype(int)
playersData['weight_temp'] = playersData['weight_temp'] / 2.2046  # conevrsion from LBS to KG

# del extra feature
playersData.drop(['height', 'weight'], axis=1, inplace=True)

# rename feature
playersData.rename(columns = {'height_temp': 'height_cm', 'weight_temp': 'weight_kg'}, inplace=True)
playersData.shape

(18936, 46)

In [114]:
playersData.head(3)

,name,name_short,team,nationality,age,ova,pot,foot,bp,value,wage,crossing,finishing,heading accuracy,short passing,volleys,dribbling,curve,fk accuracy,long passing,ball control,acceleration,sprint speed,agility,reactions,balance,shot power,jumping,stamina,strength,long shots,aggression,interceptions,positioning,vision,penalties,composure,marking,standing tackle,sliding tackle,gk diving,gk handling,gk positioning,gk reflexes,height_cm,weight_kg
0,Paulo Henrique Chagas de Lima,19 Ganso,Amiens SC,Brazil,28,75,75,Left,CAM,€6.5M,€20K,77,72,56,81,75,80,80,76,79,83,36,34,68,67,54,77,29,56,67,75,56,47,71,78,76,75,31,29,30,9,12,7,11,182.88,78.019
1,Brandon Williams,B. Williams,Manchester United,England,18,71,86,Right,LB,€4.5M,€14K,63,54,59,69,53,72,57,30,59,70,79,84,76,68,64,68,72,74,62,50,80,71,65,60,41,70,68,67,67,10,13,7,7,182.88,69.854
2,Alejandro Gómez,A. Gómez,Atalanta,Argentina,31,86,86,Right,CAM,€39M,€100K,83,80,38,83,72,85,82,79,74,85,94,85,92,85,94,76,70,70,46,81,56,40,82,87,72,85,50,30,34,8,11,9,6,167.64,68.040

Looks fine! Time to save.

In [115]:
!pwd

/Users/atahankocak/ds/Projects/EPL-Wage-Estimator/notebooks

In [116]:
# save in disk.
playersData.to_csv('../../csv_files/EPL-Wage-Estimator/playersData.csv')

Every team in the dataframe belongs to a league. I need the bring the leagues for the completeness of the project. To get the leagues.

Same "offset=a_number" applies to this section of the website as well. I expect to get around 1000 teams ("offset=960 is the last page x 60 teams per page).

In [117]:
team_urls = []
for i in range(0, 1021, 20):
    team_url = 'https://sofifa.com/teams?offset={}'   
    team_urls.append(team_url.format(i))
    
len(team_urls)

52

In [118]:
# set teams dictionary
teams = {}
for team_url in team_urls:    
    
    response = requests.get(team_url)
    page = response.text
    soup = BeautifulSoup(page,"lxml")
    table = soup.find('table')
    rows = [row for row in table.find_all('tr')]
    number_of_rows = len(table.findAll(lambda tag: tag.name == 'tr' and tag.findParent('table') == table))

    for i in range(1,number_of_rows):
        league = rows[i].find_all('a')[1].text
        team = rows[i].find_all('a')[0].text
        
        teams[team] = league

In [119]:
# convert to Pandas dataframe
teamsData = pd.DataFrame.from_dict(teams, orient='index',
                              columns=['league']).reset_index()
# rename the "name" column
teamsData.rename(columns={'index': "team"}, inplace=True)

# perform sanity check (20 teams per page)
teamsData.shape

(1058, 2)

In [120]:
teamsData.head()

                team                       league
0  Manchester United   English Premier League (1)
1        Real Madrid   Spain Primera Division (1)
2       FC Barcelona   Spain Primera Division (1)
3            Arsenal   English Premier League (1)
4   Newcastle United   English Premier League (1)

And save.

In [121]:
# save
teamsData.to_csv('../../csv_files/EPL-Wage-Estimator/teamsData.csv')

Our next stop is EPL teams actual footballer wages.

I wish to get footballer names, teams, and wages...anything I can use to create a common key in both dataframes and merge.

In [122]:
# call the page, request data, and save in a list

url = 'https://www.spotrac.com/epl/'
response = requests.get(url)
page = response.text
soup = BeautifulSoup(page,"lxml")
h3 = soup.find_all('h3')
teams=[element.text for element in h3]
teams

['Your Privacy',
 'Necessary Cookies',
 'Traffic & Performance',
 'Marketing & Advertising',
 'Privacy Policy',
 'AFC Bournemouth',
 'Arsenal F.C.',
 'Aston Villa F.C.',
 'Brighton & Hove Albion',
 'Burnley F.C.',
 'Chelsea F.C.',
 'Crystal Palace',
 'Everton F.C.',
 'Leicester City',
 'Liverpool F.C.',
 'Manchester City F.C.',
 'Manchester United F.C.',
 'Newcastle United F.C.',
 'Norwich City F.C.',
 'Sheffield United F.C.',
 'Southampton F.C.',
 'Tottenham Hotspur F.C.',
 'Watford',
 'West Ham United F.C.',
 'Wolverhampton Wanderers F.C.',
 '']

The list has some elements those are not team names. I will exclude the first 5 rows and the last row.

In [123]:
teams = teams[5:-1]

In [124]:
teams

['AFC Bournemouth',
 'Arsenal F.C.',
 'Aston Villa F.C.',
 'Brighton & Hove Albion',
 'Burnley F.C.',
 'Chelsea F.C.',
 'Crystal Palace',
 'Everton F.C.',
 'Leicester City',
 'Liverpool F.C.',
 'Manchester City F.C.',
 'Manchester United F.C.',
 'Newcastle United F.C.',
 'Norwich City F.C.',
 'Sheffield United F.C.',
 'Southampton F.C.',
 'Tottenham Hotspur F.C.',
 'Watford',
 'West Ham United F.C.',
 'Wolverhampton Wanderers F.C.']

In [125]:
len(teams)

20

Now I want to scrape the names and the weekly wages. However, the team names in the urls do not match the team names in "teams". The team section of the url does not have special chracacter or spaces, "-" is used for spaces. 

I will define a function to go over the teams list and add an additional column to match the team section of url.

So far, I figured that I need to get rid of any special char like "&", replace spaces with "-", convert "F.C." to "F.C", and use lower case chars. Also, I have to watch out for the extra space after transforming the special char "&" to "".

In [126]:
# define the function for team name conversion
def url_name(team):
    team = team.replace('& ', '').replace(' ', '-').replace('F.C.', 'F.C')
    return str(team)

In [127]:
wage_teams = [url_name(e).lower() for e in teams]

In [128]:
wage_teams

['afc-bournemouth',
 'arsenal-f.c',
 'aston-villa-f.c',
 'brighton-hove-albion',
 'burnley-f.c',
 'chelsea-f.c',
 'crystal-palace',
 'everton-f.c',
 'leicester-city',
 'liverpool-f.c',
 'manchester-city-f.c',
 'manchester-united-f.c',
 'newcastle-united-f.c',
 'norwich-city-f.c',
 'sheffield-united-f.c',
 'southampton-f.c',
 'tottenham-hotspur-f.c',
 'watford',
 'west-ham-united-f.c',
 'wolverhampton-wanderers-f.c']

Now we are ready to get the 2019- 2020 actual weekly wages of each player in EPL!

In [129]:
# get urls for teams 

wage_urls = []
for wage_team in wage_teams:
    wage_url = 'https://www.spotrac.com/epl/{}/payroll/'   
    wage_urls.append(wage_url.format(wage_team))
    
wage_urls

['https://www.spotrac.com/epl/afc-bournemouth/payroll/',
 'https://www.spotrac.com/epl/arsenal-f.c/payroll/',
 'https://www.spotrac.com/epl/aston-villa-f.c/payroll/',
 'https://www.spotrac.com/epl/brighton-hove-albion/payroll/',
 'https://www.spotrac.com/epl/burnley-f.c/payroll/',
 'https://www.spotrac.com/epl/chelsea-f.c/payroll/',
 'https://www.spotrac.com/epl/crystal-palace/payroll/',
 'https://www.spotrac.com/epl/everton-f.c/payroll/',
 'https://www.spotrac.com/epl/leicester-city/payroll/',
 'https://www.spotrac.com/epl/liverpool-f.c/payroll/',
 'https://www.spotrac.com/epl/manchester-city-f.c/payroll/',
 'https://www.spotrac.com/epl/manchester-united-f.c/payroll/',
 'https://www.spotrac.com/epl/newcastle-united-f.c/payroll/',
 'https://www.spotrac.com/epl/norwich-city-f.c/payroll/',
 'https://www.spotrac.com/epl/sheffield-united-f.c/payroll/',
 'https://www.spotrac.com/epl/southampton-f.c/payroll/',
 'https://www.spotrac.com/epl/tottenham-hotspur-f.c/payroll/',
 'https://www.spotrac.com/epl/watford/payroll/',
 'https://www.spotrac.com/epl/west-ham-united-f.c/payroll/',
 'https://www.spotrac.com/epl/wolverhampton-wanderers-f.c/payroll/']

In [130]:
# check a url
url = 'https://www.spotrac.com/epl/afc-bournemouth/payroll/'
response = requests.get(url)
page = response.text
soup = BeautifulSoup(page,"lxml")
table = soup.find('table')
rows = [row for row in table.find_all('tr')]

age = rows[2].find_all('span', class_='cap')[1].text
age

name = rows[2].find("a").text
print(name, age)

Jefferson Lerma 24

In [131]:
# set the dict for sportac wages
wages = {}
for wage_url in wage_urls:    
    
    response = requests.get(wage_url)
    page = response.text
    soup = BeautifulSoup(page,"lxml")
    table = soup.find('table')
    rows = [row for row in table.find_all('tr')]
    number_of_rows = len(table.findAll(lambda tag: tag.name == 'tr' and tag.findParent('table') == table))

    for i in range(1, number_of_rows):
        name = rows[i].find("a").text
        position = rows[i].find_all('span', class_='cap')[0].text
        age = rows[i].find_all('span', class_='cap')[1].text
        weekly_wage = rows[i].find_all('span', class_='cap info')[1].text
        team = str(" ".join(soup.find('div', class_='team-name').text.split()[:-2]))
        
        wages[name] = [age,position,team,weekly_wage]

In [132]:
# check the dictionary
len(wages)

508

The order of the key: value pairs =>> First Name & Last Name: age, team, weekly salary

In [133]:
# save to dataframe and then to csv

wagesDataEPL = pd.DataFrame.from_dict(wages, orient='index',
                                   columns=['age', 'position', 'team', 'weekly_wages']).reset_index()

# rename the "name" column
wagesDataEPL.rename(columns={'index': "name"}, inplace=True)

# perform sanity check (20 teams per page)
wagesDataEPL.shape

(508, 5)

In [134]:
wagesDataEPL.head()

              name age position             team weekly_wages
0    Callum Wilson  27        F  AFC Bournemouth     £60,000
1  Jefferson Lerma  24        M  AFC Bournemouth     £50,000
2       Steve Cook  27        D  AFC Bournemouth     £45,000
3      Joshua King  27        F  AFC Bournemouth     £45,000
4       Nathan Ake  24        D  AFC Bournemouth     £40,000

In [135]:
wagesDataEPL.shape

(508, 5)

In [136]:
# check number of teams
wagesDataEPL.team.nunique()

20

In [137]:
# check one player
wagesDataEPL[wagesDataEPL.name == 'Ryan Fredericks']

                name age position                  team weekly_wages
474  Ryan Fredericks  26        M  West Ham United F.C.     £40,000

In [138]:
# save to disk
wagesDataEPL.to_csv('../../csv_files/EPL-Wage-Estimator/wagesDataEPL.csv')

Finally, I have 3 seperate datasets:
- footballers.csv
- teams.csv
- wagesEPL.csv

*Also, I experienced an interesting memory problem while attempting to scrape the data. The following site has the command to start the jupyter to avoid the problem: https://github.com/jupyter/notebook/issues/2287*

### Merge Leagues

I have 3 seperate datasets. I want to merge them. Let's start by merging leagues into footballers. This will help us to seperate EPL from the rest.

In [139]:
# merge
playersData = pd.merge(playersData, teamsData, on='team', how='left')

In [140]:
# check for missing values
playersData.isna().sum()

name                  0
name_short            0
team                  0
nationality           0
age                   0
ova                   0
pot                   0
foot                  0
bp                    0
value                 0
wage                  0
crossing              0
finishing             0
heading accuracy      0
short passing         0
volleys               0
dribbling             0
curve                 0
fk accuracy           0
long passing          0
ball control          0
acceleration          0
sprint speed          0
agility               0
reactions             0
balance               0
shot power            0
jumping               0
stamina               0
strength              0
long shots            0
aggression            0
interceptions         0
positioning           0
vision                0
penalties             0
composure             0
marking               0
standing tackle       0
sliding tackle        0
gk diving             0
gk handling           0
gk positioning        0
gk reflexes           0
height_cm            42
weight_kg             0
league              499
dtype: int64

Let's check the missing `league` values. First, I monitor for teams.

In [141]:
playersData[playersData.league.isna()]['team'].value_counts()

                                   387
Zamora FC                           11
Vejle Boldklub                       9
NAC Breda                            9
Jeonnam Dragons                      6
KVC Westerlo                         4
Sandefjord Fotball                   4
Åtvidabergs FF                       4
Associação Académica de Coimbra      4
Triestina                            4
Stade Lavallois Mayenne FC           4
Viborg FF                            4
Roda JC Kerkrade                     4
Aalesunds FK                         4
Daejeon Citizen                      3
Longford Town                        3
Ruch Chorzów                         3
111648                               3
Xerez Club Deportivo                 2
RAEC Mons                            2
Polonia Warszawa                     2
Busan IPark                          2
Sogndal Fotball                      2
Vitória                              2
SC Cambuur                           2
Inverness Caledonian Thistle         2
RC Recreativo de Huelva              2
SV Ried                              2
Hønefoss BK                          2
União de Leiria                      1
FC Istres Ouest Provence             1
Shelbourne FC                        1
UD Salamanca                         1
Torquay United                       1
US Créteil-Lusitanos                 1
Rot-Weiß Oberhausen                  1
Name: team, dtype: int64

OK. 406 of them are teams that are not in the presented leagues. I will assign them to "Rest of the World" league. That leaves 123 without a team. I can assign them to "Free Agent".

In [142]:
# prepare the masks
mask1 = playersData['team'] == ''
mask2 = playersData['team'] != ''

# apply the masks :)
playersData['league'] = playersData['league'].mask(mask1, playersData['league'].fillna("Rest of the World"))
playersData['league'] = playersData['league'].mask(mask2, playersData['league'].fillna("Free Agent"))

In [143]:
# sanity checks
print(playersData.league.isna().sum())
print(playersData[playersData.league == 'Free Agent'].shape)
print(playersData[playersData.league == 'Rest of the World'].shape)

0
(112, 47)
(387, 47)

By the way, I remember seeing a space in the begining of the string legue data. Let's fix that.

In [144]:
playersData['league'] = playersData['league'].str.strip()
playersData.league.unique()

array(['French Ligue 1 (1)', 'English Premier League (1)',
       'Italian Serie A (1)', 'Holland Eredivisie (1)',
       'German 1. Bundesliga (1)', 'Czech Republic Gambrinus Liga (1)',
       'Portuguese Liga ZON SAGRES (1)',
       'Argentina Primera División \xa0(1)',
       'Belgian Jupiler Pro League (1)', 'Spain Primera Division (1)',
       'USA Major League Soccer (1)', 'Uruguayan Primera División (1)',
       'Austrian Football Bundesliga (1)',
       'English League Championship (2)', 'Spanish Segunda División (2)',
       'Scottish Premiership (1)', 'German 2. Bundesliga (2)',
       'Danish Superliga (1)', 'Swiss Super League (1)',
       'Croatian Prva HNL (1)', 'Colombian Liga Postobón (1)',
       'English League One (3)', 'Ukrainian Premier League (1)',
       'Chinese Super League (1)', 'Australian Hyundai A-League (1)',
       'Russian Premier League (1)', 'Mexican Liga MX (1)',
       'Rest of the World', 'Campeonato Brasileiro Série A (1)',
       'Polish T-Mobile Ekstraklasa (1)',
       'Chilian Campeonato Nacional (1)', 'German 3. Bundesliga (3)',
       'Japanese J. League Division 1 (1)', 'Greek Super League (1)',
       'Swedish Allsvenskan (1)', 'Turkish Süper Lig (1)',
       'French Ligue 2 (2)', 'Saudi Abdul L. Jameel League (1)',
       'Italian Serie B (2)', 'English League Two (4)',
       'Romanian Liga I (1)', 'Norwegian Eliteserien (1)',
       'Ecuadorian Serie A (1)', 'Paraguayan Primera División (1)',
       'Korean K League Classic (1)',
       'Rep. Ireland Airtricity League (1)', 'Free Agent',
       'Finnish Veikkausliiga (1)',
       'Liga de Fútbol Profesional Boliviano (1)',
       'UAE Arabian Gulf League (1)', 'Peruvian Primera División (1)',
       'South African Premier Division (1)',
       'Venezuelan Primera División (1)',
       'Campeonato Brasileiro Série B (2)'], dtype=object)

Excellent! I may not even need these other leagues, hence the fix. But having them intact can be essential in later stages of this project. I may extend the model to predict the entire EU at some point. That remains to be seen.

Thats being said, it is time to get EPL specific observations! Let's check the team count and make sure we have 20 teams in EPL.

In [145]:
# check EPL team count
playersData[playersData.league == "English Premier League (1)"]['team'].nunique()

20

In [204]:
# initilize the EPL only dataset
playersDataEPL = playersData[playersData['league'] == 'English Premier League (1)']

### Merge Actual Wages

Time to bring in actual wages data. Let's take another look at both datasets.

In [205]:
# wages
wagesDataEPL.head()

,name,age,position,team,weekly_wages,_team,last_name,merge_key
0,Callum Wilson,27,F,AFC Bournemouth,"£60,000",Bournemouth,Wilson,BournemouthWilsonC
1,Jefferson Lerma,24,M,AFC Bournemouth,"£50,000",Bournemouth,Lerma,BournemouthLermaJ
2,Steve Cook,27,D,AFC Bournemouth,"£45,000",Bournemouth,Cook,BournemouthCookS
3,Joshua King,27,F,AFC Bournemouth,"£45,000",Bournemouth,King,BournemouthKingJ
4,Nathan Ake,24,D,AFC Bournemouth,"£40,000",Bournemouth,Ake,BournemouthAkeN

In [206]:
# players
playersDataEPL.head(3)

,name,name_short,team,nationality,age,ova,pot,foot,bp,value,wage,crossing,finishing,heading accuracy,short passing,volleys,dribbling,curve,fk accuracy,long passing,ball control,acceleration,sprint speed,agility,reactions,balance,shot power,jumping,stamina,strength,long shots,aggression,interceptions,positioning,vision,penalties,composure,marking,standing tackle,sliding tackle,gk diving,gk handling,gk positioning,gk reflexes,height_cm,weight_kg,league
1,Brandon Williams,B. Williams,Manchester United,England,18,71,86,Right,LB,€4.5M,€14K,63,54,59,69,53,72,57,30,59,70,79,84,76,68,64,68,72,74,62,50,80,71,65,60,41,70,68,67,67,10,13,7,7,182.88,69.854,English Premier League (1)
6,Mason Greenwood,M. Greenwood,Manchester United,England,17,73,89,Left,ST,€8M,€15K,64,74,64,69,61,72,67,65,65,70,78,81,78,70,64,76,63,69,65,72,55,34,73,69,64,73,35,39,33,5,6,9,8,185.42,69.854,English Premier League (1)
9,Bukayo Saka,B. Saka,Arsenal,England,17,74,89,Left,LM,€11M,€8K,79,62,45,68,55,77,72,48,63,73,86,82,82,67,80,64,56,76,58,60,64,53,68,65,58,70,55,58,62,7,8,9,13,177.80,64.864,English Premier League (1)

I can use the names as keys for sure. But it seems a bit risky to use name by itself. I can add teams to make the keys more unique. Lets check the teams.

In [207]:
print(sorted(wagesDataEPL.team.unique()))
print(sorted(playersDataEPL.team.unique()))

['AFC Bournemouth', 'Arsenal F.C.', 'Aston Villa F.C.', 'Brighton & Hove Albion', 'Burnley F.C.', 'Chelsea F.C.', 'Crystal Palace', 'Everton F.C.', 'Leicester City', 'Liverpool F.C.', 'Manchester City F.C.', 'Manchester United F.C.', 'Newcastle United F.C.', 'Norwich City F.C.', 'Sheffield United F.C.', 'Southampton F.C.', 'Tottenham Hotspur F.C.', 'Watford', 'West Ham United F.C.', 'Wolverhampton Wanderers F.C.']
['Arsenal', 'Aston Villa', 'Bournemouth', 'Brighton & Hove Albion', 'Burnley', 'Chelsea', 'Crystal Palace', 'Everton', 'Leicester City', 'Liverpool', 'Manchester City', 'Manchester United', 'Newcastle United', 'Norwich City', 'Sheffield United', 'Southampton', 'Tottenham Hotspur', 'Watford', 'West Ham United', 'Wolverhampton Wanderers']

I need to make them similar. I can get rid of AFC and F.C. to make it happen.

In [208]:
# define function for name conversion
def name_trans(team):
    team = team.replace("AFC ", "").replace(" F.C.", "")
    return str(team)

# define function to compare the lists
from collections import defaultdict

def list_match(list1, list2):
    mydict = defaultdict(int)
    for e in list1:
        mydict[e]+=1
    for e in list2:
        mydict[e]-=1
        if mydict[e]<0:
            return 'No match'
    return 'Match!'

In [209]:
# get the teams from both datasets to list level
wageTeams = list(wagesDataEPL.team.unique())
playerTeams = list(playersDataEPL.team.unique())

In [210]:
# execute the functions
_wageTeams = [name_trans(e) for e in wageTeams]
print(list_match(_wageTeams, playerTeams))

Match!

Great! Now we have matching teams. Let's map them in wageDataEPL.

In [211]:
# form dict
teams_dict = {}
for e in wageTeams:
    teams_dict[e] = name_trans(e)
    
# map
wagesDataEPL['_team'] = wagesDataEPL['team'].map(teams_dict)

In [212]:
wagesDataEPL.head()

,name,age,position,team,weekly_wages,_team,last_name,merge_key
0,Callum Wilson,27,F,AFC Bournemouth,"£60,000",Bournemouth,Wilson,BournemouthWilsonC
1,Jefferson Lerma,24,M,AFC Bournemouth,"£50,000",Bournemouth,Lerma,BournemouthLermaJ
2,Steve Cook,27,D,AFC Bournemouth,"£45,000",Bournemouth,Cook,BournemouthCookS
3,Joshua King,27,F,AFC Bournemouth,"£45,000",Bournemouth,King,BournemouthKingJ
4,Nathan Ake,24,D,AFC Bournemouth,"£40,000",Bournemouth,Ake,BournemouthAkeN

So, we have first and last names in the `name` field for both datasets. Let's check one team.

In [213]:
print(sorted(wagesDataEPL[wagesDataEPL['_team'] == 'Arsenal']['name']))
print(sorted(playersDataEPL[playersDataEPL['team'] == 'Arsenal']['name']))

['Ainsley Maitland-Niles', 'Alexandre Lacazette', 'Bernd Leno', 'Calum Chambers', 'Dani Ceballos', 'David Luiz', 'Dejan Iliev', 'Emiliano Martinez', 'Gabriel Martinelli', 'Granit Xhaka', 'Hector Bellerin', 'Kieran Tierney', 'Konstantinos Mavropanos', 'Lucas Torreira', 'Matteo Guendouzi', 'Mesut Ozil', 'Nicolas Pepe', 'Pierre-Emerick Aubameyang', 'Rob Holding', 'Sead Kolasinac', 'Shkodran Mustafi', 'Sokratis Papastathopoulos']
['Ainsley Maitland-Niles', 'Alexandre Lacazette', 'Bernd Leno', 'Bukayo Saka', 'Calum Chambers', 'Charlie Gilmour', 'Cédric Ricardo Alves Soares', 'Daniel Ceballos Fernández', 'David Luiz Moreira Marinho', 'Eddie Nketiah', 'Folarin Balogun', 'Gabriel Teodoro Martinelli Silva', 'Granit Xhaka', 'Harrison Clarke', 'Héctor Bellerín Moruno', 'Joseph Willock', 'Kieran Tierney', 'Lucas Torreira', 'Matt Macey', 'Mattéo Guendouzi', 'Mesut Özil', 'Mikel Arteta Amatriain', 'Nathan Tormey', 'Nicolas Pépé', 'Pablo Marí Villar', 'Per Mertesacker', 'Petr Čech', 'Pierre-Emerick Aubameyang', 'Reiss Nelson', 'Rob Holding', 'Robbie Burton', 'Ryan Huddart', 'Sead Kolašinac', 'Shkodran Mustafi', 'Sokratis Papastathopoulos', 'Tolaji Bola', 'Trae Coyle', 'Zech Medley']

This does not work with full names. Wages datasets has simpler versions. Players dataset has longer version. But, I can solve this by just focusing on last names. Then I create a new feature `lastName`

In [214]:
# players df
playersDataEPL['last_name'] = playersDataEPL['name_short'].str.rsplit(' ', 1).str[-1]

# wages df
wagesDataEPL['last_name'] = wagesDataEPL['name'].str.rsplit(' ', 1).str[-1]

/Users/atahankocak/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [215]:
# quick check
playersDataEPL.head(3)

,name,name_short,team,nationality,age,ova,pot,foot,bp,value,wage,crossing,finishing,heading accuracy,short passing,volleys,dribbling,curve,fk accuracy,long passing,ball control,acceleration,sprint speed,agility,reactions,balance,shot power,jumping,stamina,strength,long shots,aggression,interceptions,positioning,vision,penalties,composure,marking,standing tackle,sliding tackle,gk diving,gk handling,gk positioning,gk reflexes,height_cm,weight_kg,league,last_name
1,Brandon Williams,B. Williams,Manchester United,England,18,71,86,Right,LB,€4.5M,€14K,63,54,59,69,53,72,57,30,59,70,79,84,76,68,64,68,72,74,62,50,80,71,65,60,41,70,68,67,67,10,13,7,7,182.88,69.854,English Premier League (1),Williams
6,Mason Greenwood,M. Greenwood,Manchester United,England,17,73,89,Left,ST,€8M,€15K,64,74,64,69,61,72,67,65,65,70,78,81,78,70,64,76,63,69,65,72,55,34,73,69,64,73,35,39,33,5,6,9,8,185.42,69.854,English Premier League (1),Greenwood
9,Bukayo Saka,B. Saka,Arsenal,England,17,74,89,Left,LM,€11M,€8K,79,62,45,68,55,77,72,48,63,73,86,82,82,67,80,64,56,76,58,60,64,53,68,65,58,70,55,58,62,7,8,9,13,177.80,64.864,English Premier League (1),Saka

In [216]:
# quick check
wagesDataEPL.head(3)

,name,age,position,team,weekly_wages,_team,last_name,merge_key
0,Callum Wilson,27,F,AFC Bournemouth,"£60,000",Bournemouth,Wilson,BournemouthWilsonC
1,Jefferson Lerma,24,M,AFC Bournemouth,"£50,000",Bournemouth,Lerma,BournemouthLermaJ
2,Steve Cook,27,D,AFC Bournemouth,"£45,000",Bournemouth,Cook,BournemouthCookS

I combine `last_name` and `team` and first letter of `name` to create a unique key for merging. And I check the duplicates in each df.

In [217]:
# players
playersDataEPL['merge_key'] = playersDataEPL['team'] + playersDataEPL['last_name'] + playersDataEPL['name'].str[0]
wagesDataEPL['merge_key'] = wagesDataEPL['_team'] + wagesDataEPL['last_name'] + wagesDataEPL['name'].str[0]

/Users/atahankocak/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

Let's check for duplicates.

One little hurde left. It is the special characters in the alphabeth. The original names have those in players df. I will convert them to the alphabeth characters for better match.

In [218]:
playersDataEPL['merge_key'] = (playersDataEPL['merge_key']
                               .str.normalize('NFKD')
                               .str.encode('ascii', errors='ignore')
                               .str.decode('utf-8'))

/Users/atahankocak/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

In [219]:
print(wagesDataEPL[wagesDataEPL['_team'] == 'Bournemouth']['merge_key'])

0        BournemouthWilsonC
1         BournemouthLermaJ
2          BournemouthCookS
3          BournemouthKingJ
4           BournemouthAkeN
5         BournemouthBorucA
6           BournemouthIbeJ
7          BournemouthCookL
8       BournemouthDanielsC
9       BournemouthGoslingD
10        BournemouthSmithA
11    BournemouthStanislasJ
12       BournemouthSurmanA
13      BournemouthFrancisS
14       BournemouthFraserR
15        BournemouthSmithB
16      BournemouthSolankeD
17       BournemouthBrooksD
18         BournemouthRicoD
19      BournemouthBillingP
20       BournemouthMephamC
21     BournemouthRamsdaleA
22      BournemouthSimpsonJ
23      BournemouthDanjumaA
24        BournemouthKellyL
25       BournemouthStaceyJ
26     BournemouthSurridgeS
27      BournemouthTraversM
28       BournemouthWilsonH
Name: merge_key, dtype: object

In [220]:
print(playersDataEPL[playersDataEPL['team'] == 'Bournemouth']['merge_key'])

294             BournemouthAkeN
384          BournemouthFraserR
493          BournemouthBrooksD
564          BournemouthWilsonH
592        BournemouthRamsdaleA
759            BournemouthCookL
760           BournemouthKellyL
889         BournemouthBillingP
896         BournemouthSolankeD
1132            BournemouthIbeJ
1191         BournemouthWilsonC
1192         BournemouthMephamC
1203           BournemouthKingJ
1376          BournemouthLermaJ
1409        BournemouthTraversM
1449     BournemouthGroeneveldA
2095        BournemouthSimpsonJ
2144           BournemouthRicoD
2405         BournemouthTaylorK
3076          BournemouthBorucA
3179       BournemouthSurridgeS
3566      BournemouthStanislasJ
4038         BournemouthStaceyJ
4367         BournemouthSurmanA
4417           BournemouthCookS
4502       BournemouthKilkennyG
5012        BournemouthGoslingD
5876        BournemouthDanielsC
6798        BournemouthCordnerT
7322        BournemouthFrancisS
7619         BournemouthJordanC
11766        BournemouthDistinS
11769         BournemouthJamesD
11892        BournemouthSaydeeC
12557       BournemouthAnthonyJ
13402    BournemouthO'FlahertyP
16623        BournemouthSeamanC
Name: merge_key, dtype: object

Looks good. I am aware of the absence of certain names from the wages df. I checked them. They are young prospects mostly. Let's do a final duplicate check and a uniqueness check. If they check out, I merge.

In [221]:
# dupes check by sorting
print(sorted(playersDataEPL['merge_key'].value_counts().head(10)))
print(sorted(wagesDataEPL['merge_key'].value_counts().head(10)))

# check the uniqueness of names in both df's
print(playersDataEPL.merge_key.nunique(), playersDataEPL.shape[0])
print(wagesDataEPL.merge_key.nunique(), wagesDataEPL.shape[0])

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
776 776
508 508

In [222]:
# merge wages into players
playersDataEPL = pd.merge(playersDataEPL, wagesDataEPL[['merge_key', 'weekly_wages']], 
                          on="merge_key", 
                          how="left")

In [223]:
playersDataEPL.head()

,name,name_short,team,nationality,age,ova,pot,foot,bp,value,wage,crossing,finishing,heading accuracy,short passing,volleys,dribbling,curve,fk accuracy,long passing,ball control,acceleration,sprint speed,agility,reactions,balance,shot power,jumping,stamina,strength,long shots,aggression,interceptions,positioning,vision,penalties,composure,marking,standing tackle,sliding tackle,gk diving,gk handling,gk positioning,gk reflexes,height_cm,weight_kg,league,last_name,merge_key,weekly_wages
0,Brandon Williams,B. Williams,Manchester United,England,18,71,86,Right,LB,€4.5M,€14K,63,54,59,69,53,72,57,30,59,70,79,84,76,68,64,68,72,74,62,50,80,71,65,60,41,70,68,67,67,10,13,7,7,182.88,69.854,English Premier League (1),Williams,Manchester UnitedWilliamsB,NaN
1,Mason Greenwood,M. Greenwood,Manchester United,England,17,73,89,Left,ST,€8M,€15K,64,74,64,69,61,72,67,65,65,70,78,81,78,70,64,76,63,69,65,72,55,34,73,69,64,73,35,39,33,5,6,9,8,185.42,69.854,English Premier League (1),Greenwood,Manchester UnitedGreenwoodM,NaN
2,Bukayo Saka,B. Saka,Arsenal,England,17,74,89,Left,LM,€11M,€8K,79,62,45,68,55,77,72,48,63,73,86,82,82,67,80,64,56,76,58,60,64,53,68,65,58,70,55,58,62,7,8,9,13,177.80,64.864,English Premier League (1),Saka,ArsenalSakaB,NaN
3,Adama Traoré Diarra,Adama Traoré,Wolverhampton Wanderers,Spain,23,78,84,Right,RM,€14M,€72K,76,66,40,68,52,92,67,42,54,82,97,96,85,64,88,78,78,77,85,65,70,41,62,68,47,73,37,38,35,13,9,12,7,177.80,72.122,English Premier League (1),Traoré,Wolverhampton WanderersTraoreA,"£43,000"
4,Gabriel Teodoro Martinelli Silva,Gabriel Martinelli,Arsenal,Brazil,18,74,88,Right,LW,€11.5M,€26K,65,74,66,66,61,76,70,49,45,75,87,86,82,74,78,68,43,76,61,60,75,37,75,65,60,73,44,40,43,10,6,6,6,180.34,68.947,English Premier League (1),Martinelli,ArsenalMartinelliG,-

In [224]:
# some more sanity checks
print(playersDataEPL.weekly_wages.shape[0] - playersDataEPL.weekly_wages.isna().sum())
print(playersDataEPL.weekly_wages.isna().sum())
print(playersDataEPL.shape)

414
362
(776, 50)

I have 371 players left without actual salary. No worries. I will develop a way to estimate them according to the actuals. I will create a ratio between the 414 actual wages and 414 sofifa wages. Then, I will apply that ratio to the missing 371 to come up with estimated actual wage. I apply this method to keep the wages aligned. 

However, I need to work on the both wage fields.

In [225]:
# 1) fix sofifa wages
# strip Euro symbol sign and "K"
playersDataEPL['_wage'] = playersDataEPL['wage'].str[1:-1]

# convert to integer
playersDataEPL['_wage'] = pd.to_numeric(playersDataEPL['_wage'])

# multiply by 1000 to get the comparable value to weekly_wages_euro
playersDataEPL['_wage'] = playersDataEPL['_wage'] * 1000

# fill NaN with zero
playersDataEPL['_wage'].fillna(0, inplace=True)

I perform similar tasks on the actual wages with the addition of currency conversion [rate](https://ycharts.com/indicators/euro_to_pound_sterling_exchange_rate) on 4/22/2020 (sofifa last udpate date).

In [226]:
# 2) fix actual wages and convert to currency
rate = 0.8792
# replace comma with ""
playersDataEPL['weekly_wages'] = playersDataEPL['weekly_wages'].str.replace(",", "")

# replace "- " with " 0 ". Then I will strip the space and BP sign from the rest, hence spaces of " 0 "
playersDataEPL['weekly_wages'] = playersDataEPL['weekly_wages'].str.replace("- ", "0")

# strip BP sign and space
playersDataEPL['weekly_wages'] = playersDataEPL['weekly_wages'].str[1:]

# convert to integer
playersDataEPL['weekly_wages'] = pd.to_numeric(playersDataEPL['weekly_wages'])

# finally convert to Euro with x-change rate of 1.17 Euro / BP (on 1/10/20, sofifa data date)
playersDataEPL['weekly_wages_euro'] = playersDataEPL['weekly_wages'] / rate

# fill nan with 0
playersDataEPL['weekly_wages_euro'].fillna(0, inplace=True)

In [227]:
# sanity check
playersDataEPL[playersDataEPL['team'] == 'Arsenal']

,name,name_short,team,nationality,age,ova,pot,foot,bp,value,wage,crossing,finishing,heading accuracy,short passing,volleys,dribbling,curve,fk accuracy,long passing,ball control,acceleration,sprint speed,agility,reactions,balance,shot power,jumping,stamina,strength,long shots,aggression,interceptions,positioning,vision,penalties,composure,marking,standing tackle,sliding tackle,gk diving,gk handling,gk positioning,gk reflexes,height_cm,weight_kg,league,last_name,merge_key,weekly_wages,_wage,weekly_wages_euro
2,Bukayo Saka,B. Saka,Arsenal,England,17,74,89,Left,LM,€11M,€8K,79,62,45,68,55,77,72,48,63,73,86,82,82,67,80,64,56,76,58,60,64,53,68,65,58,70,55,58,62,7,8,9,13,177.80,64.864,English Premier League (1),Saka,ArsenalSakaB,NaN,8000.0,0.000
4,Gabriel Teodoro Martinelli Silva,Gabriel Martinelli,Arsenal,Brazil,18,74,88,Right,LW,€11.5M,€26K,65,74,66,66,61,76,70,49,45,75,87,86,82,74,78,68,43,76,61,60,75,37,75,65,60,73,44,40,43,10,6,6,6,180.34,68.947,English Premier League (1),Martinelli,ArsenalMartinelliG,NaN,26000.0,0.000
27,Mattéo Guendouzi,M. Guendouzi,Arsenal,France,20,77,86,Right,CM,€12.5M,€46K,67,56,67,79,55,75,72,67,80,77,73,75,73,75,70,74,68,79,72,68,78,73,67,79,62,77,72,73,70,6,13,13,11,185.42,79.833,English Premier League (1),Guendouzi,ArsenalGuendouziM,40000.0,46000.0,45495.905
47,Eddie Nketiah,E. Nketiah,Arsenal,England,20,70,85,Right,ST,€3.9M,€30K,43,73,53,61,63,72,49,38,46,68,86,83,80,70,72,64,73,69,59,62,52,19,74,53,57,65,22,19,15,12,10,9,5,175.26,72.122,English Premier League (1),Nketiah,ArsenalNketiahE,NaN,30000.0,0.000
53,Nicolas Pépé,N. Pépé,Arsenal,Ivory Coast,24,82,87,Left,CAM,€29.5M,€89K,78,77,57,75,70,86,79,79,67,81,89,91,89,83,81,81,68,82,68,79,43,28,81,80,85,78,36,27,25,11,14,6,8,182.88,73.029,English Premier League (1),Pépé,ArsenalPepeN,140000.0,89000.0,159235.669
55,Kieran Tierney,K. Tierney,Arsenal,Scotland,22,77,86,Left,LB,€12.5M,€55K,77,52,59,73,27,75,72,56,68,74,86,89,76,74,77,79,80,85,76,66,82,71,67,72,36,74,73,74,74,13,16,12,13,177.80,76.204,English Premier League (1),Tierney,ArsenalTierneyK,NaN,55000.0,0.000
64,Pierre-Emerick Aubameyang,P. Aubameyang,Arsenal,Gabon,30,88,88,Right,ST,€57M,€200K,76,91,75,77,84,80,81,76,64,82,91,94,77,88,68,82,75,78,74,78,43,48,93,77,78,87,27,29,36,6,9,9,9,187.96,79.833,English Premier League (1),Aubameyang,ArsenalAubameyangP,200000.0,200000.0,227479.527
69,Joseph Willock,J. Willock,Arsenal,England,19,71,85,Right,CAM,€5M,€24K,54,60,41,74,52,74,54,46,69,72,77,76,73,65,72,72,60,73,66,64,66,62,70,69,57,62,56,62,53,11,6,8,9,185.42,76.204,English Premier League (1),Willock,ArsenalWillockJ,NaN,24000.0,0.000
73,Daniel Ceballos Fernández,Dani Ceballos,Arsenal,Spain,22,81,86,Right,CM,€23.5M,€82K,74,68,41,82,62,83,77,63,80,85,73,67,80,80,79,76,51,77,65,73,76,76,76,80,55,80,67,75,74,12,15,7,13,177.80,68.040,English Premier League (1),Ceballos,ArsenalCeballosD,51923.0,82000.0,59057.097
80,Reiss Nelson,R. Nelson,Arsenal,England,19,73,83,Right,RM,€6.5M,€35K,65,69,39,68,55,78,66,67,58,76,87,85,84,64,76,67,41,69,52,54,42,42,70,67,54,60,24,37,37,12,12,11,15,180.34,74.844,English Premier League (1),Nelson,ArsenalNelsonR,NaN,35000.0,0.000
87,Héctor Bellerín Moruno,Héctor Bellerín,Arsenal,Spain,24,79,84,Right,RWB,€15M,€65K,76,52,60,77,41,77,63,50,59,78,89,88,79,79,77,52,64,76,58,43,72,78,67,66,62,70,76,78,80,8,14,13,12,177.80,73.936,English Premier League (1),Bellerín,ArsenalBellerinH,110000.0,65000.0,125113.740
104,Ainsley Maitland-Niles,A. Maitland-Niles,Arsenal,England,21,75,83,Right,RM,€9M,€41K,70,56,54,74,44,77,60,36,67,76,83,87,79,72,71,65,55,78,66,62,58,70,66,72,54,77,67,73,69,15,9,10,13,177.80,69.854,English Premier League (1),Maitland-Niles,ArsenalMaitland-NilesA,35000.0,41000.0,39808.917
109,Lucas Torreira,L. Torreira,Arsenal,Uruguay,23,81,86,Right,CDM,€21.5M,€74K,72,61,59,80,65,78,70,74,75,80,77,72,85,79,91,78,52,84,66,74,86,84,68,74,48,78,80,84,77,5,5,7,9,167.64,64.864,English Premier League (1),Torreira,ArsenalTorreiraL,75000.0,74000.0,85304.823
119,Mesut Özil,M. Özil,Arsenal,Germany,30,83,83,Left,CAM,€24.5M,€110K,83,70,51,89,80,83,84,76,82,89,68,62,75,82,71,70,45,64,56,67,44,24,80,90,67,83,24,16,19,6,14,6,14,180.34,71.215,English Premier League (1),Özil,ArsenalOzilM,350000.0,110000.0,398089.172
129,Alexandre Lacazette,A. Lacazette,Arsenal,France,28,84,84,Right,ST,€32M,€140K,68,83,74,79,81,84,74,74,70,85,78,76,84,84,83,87,76,77,75,78,74,42,84,78,76,83,39,51,32,11,6,5,6,175.26,77.111,English Premier League (1),Lacazette,ArsenalLacazetteA,182063.0,140000.0,207078.025
187,Rob Holding,R. Holding,Arsenal,England,23,76,83,Right,CB,€10M,€52K,52,30,75,71,27,62,33,30,61,67,58,61,58,70,66,48,77,65,76,27,72,77,40,57,38,75,77,78,76,14,11,14,13,187.96,81.194,English Premier League (1),Holding,ArsenalHoldingR,25000.0,52000.0,28434.941
189,Bernd Leno,B. Leno,Arsenal,Germany,27,85,87,Right,GK,€32.5M,€99K,9,9,13,50,10,16,9,8,48,35,55,56,52,81,44,59,73,43,70,14,28,25,7,56,23,66,27,15,18,85,83,84,86,190.50,82.101,English Premier League (1),Leno,ArsenalLenoB,100000.0,99000.0,113739.763
207,Pablo Marí Villar,Pablo Marí,Arsenal,Spain,25,76,81,Left,CB,€9M,€57K,32,38,82,69,28,41,27,30,63,60,55,51,49,74,37,53,75,75,87,40,80,72,34,37,31,67,77,74,70,6,14,13,12,193.04,87.091,English Premier League (1),Marí,ArsenalMariP,NaN,57000.0,0.000
210,Granit Xhaka,G. Xhaka,Arsenal,Switzerland,26,80,81,Left,CDM,€15.5M,€80K,71,50,62,85,50,66,76,77,85,80,48,55,49,73,61,90,30,82,81,75,92,72,67,80,63,67,70,71,68,7,8,7,13,185.42,79.833,English Premier League (1),Xhaka,ArsenalXhakaG,100000.0,80000.0,113739.763
214,Calum Chambers,C. Chambers,Arsenal,England,24,76,81,Right,CDM,€9.5M,€52K,69,54,73,76,47,66,60,49,70,76,66,71,60,74,66,60,71,76,77,58,77,75,54,63,54,64,73,78,74,11,14,7,12,182.88,87.091,English Premier League (1),Chambers,ArsenalChambersC,50000.0,52000.0,56869.882
225,Sead Kolašinac,S. Kolašinac,Arsenal,Bosnia Herzegovina,26,77,80,Left,CB,€9.5M,€64K,74,57,74,78,55,75,61,42,62,76,71,79,64,74,55,82,76,79,90,58,93,70,73,74,54,72,71,79,77,15,9,7,9,182.88,86.183,English Premier League (1),Kolašinac,ArsenalKolasinacS,100000.0,64000.0,113739.763
228,Zech Medley,Z. Medley,Arsenal,England,18,63,81,Left,CB,€700K,€4K,34,25,62,43,35,42,34,29,37,50,60,68,55,56,51,41,70,63,72,27,52,60,32,37,43,50,61,70,63,10,11,10,14,195.58,78.926,English Premier League (1),Medley,ArsenalMedleyZ,NaN,4000.0,0.000
229,David Luiz Moreira Marinho,David Luiz,Arsenal,Brazil,32,81,81,Right,CB,€11.5M,€86K,68,55,80,77,63,68,70,72,83,79,63,64,66,77,56,81,78,71,78,72,86,81,54,71,75,75,78,81,79,11,12,7,14,187.96,86.183,English Premier League (1),Luiz,ArsenalLuizD,125673.0,86000.0,142940.173
239,Shkodran Mustafi,S. Mustafi,Arsenal,Germany,27,79,81,Right,CB,€13M,€76K,53,58,81,75,51,53,55,47,69,70,55,62,63,76,67,66,81,68,78,52,86,75,49,55,54,73,74,79,78,11,9,10,6,182.88,83.008,English Premier League (1),Mustafi,ArsenalMustafiS,90000.0,76000.0,102365.787
242,Sokratis Papastathopoulos,Sokratis,Arsenal,Greece,31,81,81,Right,CB,€13M,€86K,47,47,83,64,50,58,29,35,58,60,68,76,52,77,62,77,82,69,87,48,88,76,49,45,38,77,80,81,80,6,8,12,5,185.42,83.915,English Premier League (1),Sokratis,ArsenalSokratisS,NaN,86000.0,0.000
277,Folarin Balogun,F. Balogun,Arsenal,England,17,60,81,Right,ST,€450K,€2K,37,62,45,44,43,57,43,37,33,57,77,74,72,60,64,60,54,68,64,52,49,18,63,45,52,60,18,15,16,10,12,13,10,177.80,69.854,English Premier League (1),Balogun,ArsenalBalogunF,NaN,2000.0,0.000
335,Cédric Ricardo Alves Soares,Cédric,Arsenal,Portugal,27,75,75,Right,RB,€6M,€57K,70,57,65,75,68,75,66,64,69,76,77,76,73,74,83,76,72,84,59,70,75,74,71,65,60,69,68,76,74,11,14,12,11,172.72,67.132,English Premier League (1),Cédric,ArsenalCedricC,NaN,57000.0,0.000
365,Harrison Clarke,H. Clarke,Arsenal,England,18,57,76,Right,CB,€200K,€3K,45,39,55,48,30,47,44,40,45,51,64,64,60,55,62,38,51,65,62,41,52,53,43,52,46,50,56,58,57,14,15,7,13,177.80,67.132,English Premier League (1),Clarke,ArsenalClarkeH,NaN,3000.0,0.000
435,Petr Čech,19 P. Čech,Arsenal,Czech Republic,36,81,81,Left,GK,€2.4M,€60K,19,12,19,35,17,12,13,19,33,22,35,38,46,75,34,21,50,32,63,11,17,23,13,53,23,63,12,13,12,77,82,83,79,195.58,89.812,English Premier League (1),Čech,ArsenalCechP,NaN,60000.0,0.000
459,Tolaji Bola,T. Bola,Arsenal,England,20,57,70,Left,LB,€180K,€7K,49,36,54,48,35,46,44,32,36,45,69,72,66,52,62,47,66,58,62,29,55,53,41,36,42,49,54,61,60,8,13,12,5,187.96,79.833,English Premier League (1),Bola,ArsenalBolaT,NaN,7000.0,0.000
470,Matt Macey,M. Macey,Arsenal,England,24,66,72,Right,GK,€675K,€12K,18,16,16,27,16,16,16,17,24,19,38,40,37,59,33,50,52,33,67,16,25,15,12,36,22,52,11,11,14,63,66,64,68,198.12,92.987,English Premier League (1),Macey,ArsenalMaceyM,NaN,12000.0,0.000
515,Trae Coyle,T. Coyle,Arsenal,England,18,57,75,Right,RM,€210K,€4K,51,50,27,57,40,57,52,45,55,55,73,70,68,50,70,56,46,64,42,49,33,18,55,54,44,51,15,27,22,13,9,14,11,177.80,74.844,English Premier League (1),Coyle,ArsenalCoyleT,NaN,4000.0,0.000
563,Per Mertesacker,18 P. Mertesacker,Arsenal,Germany,32,80,80,Right,CB,€8.5M,€110K,38,36,83,65,30,39,39,45,56,64,25,26,25,84,28,71,29,52,81,25,68,86,43,58,42,87,84,85,80,12,13,12,8,198.12,89.812,English Premier League (1),Mertesacker,ArsenalMertesackerP,NaN,110000.0,0.000
567,Nathan Tormey,N. Tormey,Arsenal,England,19,58,72,Left,CAM,€275K,€6K,55,50,43,57,49,60,66,63,51,57,74,72,71,52,68,60,47,50,50,56,42,24,50,57,52,56,18,36,35,8,9,13,12,170.18,67.132,English Premier League (1),Tormey,ArsenalTormeyN,NaN,6000.0,0.000
600,Mikel Arteta Amatriain,16 Mikel Arteta,Arsenal,Spain,33,78,78,Right,CM,€5M,€70K,77,68,62,83,75,73,79,79,83,81,46,44,62,72,75,77,65,65,63,72,75,75,70,79,85,,70,70,65,15,14,11,12,175.26,63.957,English Premier League (1),Arteta,ArsenalArtetaM,NaN,70000.0,0.000
673,Robbie Burton,R. Burton,Arsenal,Wales,19,59,75,Right,CAM,€325K,€6K,47,43,38,65,41,56,49,51,61,55,58,60,62,62,67,50,34,58,40,50,42,42,53,62,54,62,38,50,49,11,13,13,8,170.18,64.864,English Premier League (1),Burton,ArsenalBurtonR,NaN,6000.0,0.000
705,Charlie Gilmour,19 C. Gilmour,Arsenal,Scotland,19,56,73,Right,CDM,€180K,€5K,38,37,41,58,41,51,47,39,55,56,64,62,65,54,74,42,55,64,69,46,56,49,51,54,36,53,48,54,49,13,6,9,14,182.88,68.947,English Premier League (1),Gilmour,ArsenalGilmourC,NaN,5000.0,0.000
775,Ryan Huddart,18 R. Huddart,Arsenal,England,20,58,67,Right,GK,€150K,€7K,13,19,14,23,12,17,21,15,18,27,39,40,32,58,46,21,52,32,59,20,19,24,12,12,24,32,21,16,13,63,55,49,60,195.58,93.895,English Premier League (1),Huddart,ArsenalHuddartR,NaN,7000.0,0.000

In [228]:
# fix the missing wages via ratio
_mask = playersDataEPL['weekly_wages_euro'] != 0
_df = playersDataEPL[_mask]
_df = _df[['weekly_wages_euro', '_wage']]
_df['_ratio'] = _df['weekly_wages_euro'] / _df['_wage']
myRatio = _df._ratio.mean()
print(f"Multiply SoFIFA wage with {myRatio} to get the estimated actual wage.")

Multiply SoFIFA wage with 1.025033040108696 to get the estimated actual wage.

In [229]:
# replace null rows with the adjusted weekly_wage from sofifa
playersDataEPL.loc[playersDataEPL['weekly_wages_euro'] == 0, 'weekly_wages_euro'] = playersDataEPL['_wage'] * myRatio

In [230]:
# drop temp features and rename
playersDataEPL.drop(['_wage', 'weekly_wages', 'merge_key', 'name', 'wage'],
                    axis=1,
                    inplace=True)

playersDataEPL.rename(columns={'weekly_wages_euro': 'wage'}, inplace=True)

In [231]:
# sanity checks
print(f"There must be only one league in this dataset and it is {playersDataEPL['league'].unique()}")
print(f"There must be {playersDataEPL['team'].nunique()} teams in this dataset.")

There must be only one league in this dataset and it is ['English Premier League (1)']
There must be 20 teams in this dataset.

In [232]:
playersDataEPL.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 776 entries, 0 to 775
Data columns (total 47 columns):
name_short          776 non-null object
team                776 non-null object
nationality         776 non-null object
age                 776 non-null object
ova                 776 non-null object
pot                 776 non-null object
foot                776 non-null object
bp                  776 non-null object
value               776 non-null object
crossing            776 non-null object
finishing           776 non-null object
heading accuracy    776 non-null object
short passing       776 non-null object
volleys             776 non-null object
dribbling           776 non-null object
curve               776 non-null object
fk accuracy         776 non-null object
long passing        776 non-null object
ball control        776 non-null object
acceleration        776 non-null object
sprint speed        776 non-null object
agility             776 non-null object
reactions           776 non-null object
balance             776 non-null object
shot power          776 non-null object
jumping             776 non-null object
stamina             776 non-null object
strength            776 non-null object
long shots          776 non-null object
aggression          776 non-null object
interceptions       776 non-null object
positioning         776 non-null object
vision              776 non-null object
penalties           776 non-null object
composure           776 non-null object
marking             776 non-null object
standing tackle     776 non-null object
sliding tackle      776 non-null object
gk diving           776 non-null object
gk handling         776 non-null object
gk positioning      776 non-null object
gk reflexes         776 non-null object
height_cm           776 non-null float64
weight_kg           776 non-null float64
league              776 non-null object
last_name           776 non-null object
wage                776 non-null float64
dtypes: float64(3), object(44)
memory usage: 291.0+ KB

And I wish to check if anyone is playing for free!

In [233]:
# checking players with $0 wage
mask = playersDataEPL['wage'] == 0
playersDataEPL[mask]

,name_short,team,nationality,age,ova,pot,foot,bp,value,crossing,finishing,heading accuracy,short passing,volleys,dribbling,curve,fk accuracy,long passing,ball control,acceleration,sprint speed,agility,reactions,balance,shot power,jumping,stamina,strength,long shots,aggression,interceptions,positioning,vision,penalties,composure,marking,standing tackle,sliding tackle,gk diving,gk handling,gk positioning,gk reflexes,height_cm,weight_kg,league,last_name,wage
625,11 E. van der Sar,Manchester United,Netherlands,39,83,87,Right,GK,€0,14,11,12,27,12,13,12,11,27,22,50,41,57,68,51,29,60,46,68,11,57,31,23,40,24,,12,10,11,82,87,93,75,198.12,88.905,English Premier League (1),Sar,0.0
647,11 P. Vieira,Manchester City,France,34,76,87,Right,CDM,€0,62,40,82,79,62,63,65,56,73,75,58,61,66,72,79,75,78,68,84,68,86,83,74,79,73,,68,79,78,10,9,15,15,193.04,82.101,English Premier League (1),Vieira,0.0
660,09 Fábio Paim,Chelsea,Portugal,20,70,78,Right,CF,€0,66,49,42,57,,83,,65,53,78,84,78,,63,,65,,56,54,50,42,50,54,,52,,28,28,,9,21,21,21,175.26,66.225,English Premier League (1),Paim,0.0
665,11 G. Neville,Manchester United,England,35,76,82,Right,CB,€0,72,31,75,71,55,44,56,33,61,64,64,70,51,72,67,47,70,65,74,28,87,85,45,70,32,,78,81,83,12,9,6,11,177.80,78.926,English Premier League (1),Neville,0.0
667,11 R. Pires,Aston Villa,France,36,75,84,Right,CAM,€0,85,73,58,83,68,79,85,72,78,82,60,64,57,63,65,70,59,48,64,75,46,44,77,88,79,,32,28,26,6,6,14,10,187.96,79.833,English Premier League (1),Pires,0.0
716,11 A. Blackwood,Tottenham Hotspur,England,18,53,64,Right,CB,€0,29,17,62,37,17,14,24,18,34,32,55,60,45,46,60,19,61,48,63,16,52,36,11,27,27,,51,58,53,5,9,6,11,175.26,74.844,English Premier League (1),Blackwood,0.0
717,11 R. Hamed,Tottenham Hotspur,England,21,53,63,Right,ST,€0,32,60,46,40,52,42,36,30,29,43,64,67,62,54,48,51,54,51,58,49,30,15,46,48,56,,18,21,12,12,12,15,12,182.88,84.823,English Premier League (1),Hamed,0.0
718,09 J. Jeffery,West Ham United,England,18,54,70,Right,ST,€0,37,61,41,45,,39,,26,23,54,66,73,,52,,54,,41,38,66,44,50,55,,36,,22,33,,11,20,20,20,182.88,84.823,English Premier League (1),Jeffery,0.0
721,10 Sylvinho,Manchester City,Brazil,35,77,84,Left,LB,€0,80,45,77,77,,74,,50,74,79,69,70,,71,,76,,67,70,71,70,83,84,,80,,80,83,,8,24,24,24,172.72,66.225,English Premier League (1),10 Sylvinho,0.0
727,09 A. Van der Meyde,Everton,Netherlands,28,69,81,Right,RW,€0,70,61,47,61,,70,,76,66,77,72,71,,60,,77,,30,69,72,48,61,72,,74,,42,31,,10,21,21,21,177.80,77.111,English Premier League (1),Meyde,0.0
729,09 D. Mills,Manchester City,England,31,66,76,Right,RB,€0,50,33,70,56,,53,,33,50,64,60,65,,62,,62,,70,80,38,96,68,65,,62,,60,64,,8,21,21,21,177.80,73.936,English Premier League (1),Mills,0.0
730,09 M. Poom,Watford,Estonia,36,64,80,Left,GK,€0,27,38,27,24,,21,,5,70,38,49,54,,51,,29,,50,71,35,66,58,18,,63,,29,28,,62,67,66,62,193.04,84.823,English Premier League (1),Poom,0.0

I know these players. They are not truly active. I think, they are in the squad for training and motivational reasons. They are the icons of their teams. I want to exclude these special players.

In [234]:
# new dataset without the players with $0 wage
playersDataEPL = playersDataEPL[~mask].reset_index()
del playersDataEPL['index']

In [235]:
# check
playersDataEPL.tail(3)

,name_short,team,nationality,age,ova,pot,foot,bp,value,crossing,finishing,heading accuracy,short passing,volleys,dribbling,curve,fk accuracy,long passing,ball control,acceleration,sprint speed,agility,reactions,balance,shot power,jumping,stamina,strength,long shots,aggression,interceptions,positioning,vision,penalties,composure,marking,standing tackle,sliding tackle,gk diving,gk handling,gk positioning,gk reflexes,height_cm,weight_kg,league,last_name,wage
761,18 S. Mourgos,Norwich City,Greece,19,57,73,Right,CAM,€220K,40,60,38,63,42,59,62,65,56,62,63,60,70,53,76,64,56,63,41,61,35,37,49,55,49,57,37,41,39,15,12,16,13,175.26,66.225,English Premier League (1),Mourgos,3075.099
762,19 A. Nemane,Manchester City,France,20,60,74,Right,RW,€450K,50,54,35,47,34,66,41,29,39,58,79,82,78,55,74,50,48,62,33,43,42,14,57,55,59,50,19,19,12,14,14,15,6,170.18,62.143,English Premier League (1),Nemane,10250.330
763,18 R. Huddart,Arsenal,England,20,58,67,Right,GK,€150K,13,19,14,23,12,17,21,15,18,27,39,40,32,58,46,21,52,32,59,20,19,24,12,12,24,32,21,16,13,63,55,49,60,195.58,93.895,English Premier League (1),Huddart,7175.231

In [236]:
# save
playersDataEPL.to_csv("../../csv_files/EPL-Wage-Estimator/playersDataEPL.csv")

I want to try something different. I experinced an interesting event while I was working on paticipant data as an actuary. 
Just like I did here, I worked on the data cleansing. Then, I saved a new copy of the udpated file. And, I opened the updated version next day by loading from the csv into the acturial software ProVal. Then I noticed some null values. They were recoded as "0" in the previous version. But, they became null values in the udpate version. And I caught that when I saved and reopnened the udpate version. 

Given this short story, I want to make sure that does not happen here. Let's read in the updated file and observe.

In [237]:
# read in data
playersDataEPL = pd.read_csv("../../csv_files/EPL-Wage-Estimator/playersDataEPL.csv", index_col=0)
playersDataEPL.head(3)

,name_short,team,nationality,age,ova,pot,foot,bp,value,crossing,finishing,heading accuracy,short passing,volleys,dribbling,curve,fk accuracy,long passing,ball control,acceleration,sprint speed,agility,reactions,balance,shot power,jumping,stamina,strength,long shots,aggression,interceptions,positioning,vision,penalties,composure,marking,standing tackle,sliding tackle,gk diving,gk handling,gk positioning,gk reflexes,height_cm,weight_kg,league,last_name,wage
0,B. Williams,Manchester United,England,18,71,86,Right,LB,€4.5M,63,54,59,69,53,72,57,30,59,70,79,84,76,68,64,68,72,74,62,50,80,71,65,60,41,70.0,68,67,67,10,13,7,7,182.88,69.854,English Premier League (1),Williams,14350.463
1,M. Greenwood,Manchester United,England,17,73,89,Left,ST,€8M,64,74,64,69,61,72,67,65,65,70,78,81,78,70,64,76,63,69,65,72,55,34,73,69,64,73.0,35,39,33,5,6,9,8,185.42,69.854,English Premier League (1),Greenwood,15375.496
2,B. Saka,Arsenal,England,17,74,89,Left,LM,€11M,79,62,45,68,55,77,72,48,63,73,86,82,82,67,80,64,56,76,58,60,64,53,68,65,58,70.0,55,58,62,7,8,9,13,177.80,64.864,English Premier League (1),Saka,8200.264

In [238]:
playersDataEPL.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 764 entries, 0 to 763
Data columns (total 47 columns):
name_short          764 non-null object
team                764 non-null object
nationality         764 non-null object
age                 764 non-null int64
ova                 764 non-null int64
pot                 764 non-null int64
foot                764 non-null object
bp                  764 non-null object
value               764 non-null object
crossing            764 non-null int64
finishing           764 non-null int64
heading accuracy    764 non-null int64
short passing       764 non-null int64
volleys             764 non-null int64
dribbling           764 non-null int64
curve               764 non-null int64
fk accuracy         764 non-null int64
long passing        764 non-null int64
ball control        764 non-null int64
acceleration        764 non-null int64
sprint speed        764 non-null int64
agility             764 non-null int64
reactions           764 non-null int64
balance             764 non-null int64
shot power          764 non-null int64
jumping             764 non-null int64
stamina             764 non-null int64
strength            764 non-null int64
long shots          764 non-null int64
aggression          764 non-null int64
interceptions       764 non-null int64
positioning         764 non-null int64
vision              764 non-null int64
penalties           764 non-null int64
composure           742 non-null float64
marking             764 non-null int64
standing tackle     764 non-null int64
sliding tackle      764 non-null int64
gk diving           764 non-null int64
gk handling         764 non-null int64
gk positioning      764 non-null int64
gk reflexes         764 non-null int64
height_cm           764 non-null float64
weight_kg           764 non-null float64
league              764 non-null object
last_name           764 non-null object
wage                764 non-null float64
dtypes: float64(4), int64(35), object(8)
memory usage: 286.5+ KB

Aha! Please take a moment and look at `composure`. Let's make sure.

In [239]:
# verify
playersDataEPL.composure.isna().sum()

22

I really do not want to delete anymore records. So, I generate `composure` values based on positional averages. To illustrate, I will use `LW` average for any Left Winger with missing `composure`.

In [240]:
# get averages of each position and save in a dictionary
pos_avg_dict = dict(playersDataEPL.groupby('bp')['composure'].mean())

# udpate conditionally
playersDataEPL.loc[playersDataEPL['composure'].isna(), ['composure']] = playersDataEPL['bp'].map(pos_avg_dict)

In [241]:
# check again
playersDataEPL.composure.isna().sum()

0

Looks good. The `ova` (overall average of attributes) may need some adjustment but it would be very minor. I do not want to perfomr unless it is the last castle.

One final check to see if numbers of players per team make sense.

In [242]:
# value counts for each team
playersDataEPL.team.value_counts()

Aston Villa                44
Burnley                    42
West Ham United            42
Watford                    41
Newcastle United           41
Crystal Palace             40
Manchester United          40
Brighton & Hove Albion     39
Chelsea                    39
Arsenal                    38
Bournemouth                37
Liverpool                  37
Wolverhampton Wanderers    36
Norwich City               36
Sheffield United           36
Manchester City            36
Southampton                36
Leicester City             35
Tottenham Hotspur          35
Everton                    34
Name: team, dtype: int64

In [243]:
playersDataEPL.shape

(764, 47)

Yep! All good. We have a dataset we can work with!

In [244]:
# save...again
playersDataEPL.to_csv("../../csv_files/EPL-Wage-Estimator/playersDataEPL.csv")

Excellent! **Next stop is EDA and Linear modeling!**

In [186]:
playersDataEPL.shape

(764, 47)